Repository efcsydney/efcsydney-roster, pull requests merged in 2018-08, with the labels that each got.

#395 #371 Evaluate Wallaby.js
  client/package.json
  client/wallaby.js
  client/yarn.lock
Labels: Test

#421 #420 Fix: Position not showing in correct order
  client/src/modules/admin/services/Popup.js
Labels: Bug, Front End

#397 #385
  docker/Dockerfile-prod
  docker/docker-compose.yml
  docker_deploy.sh
Labels: Bug

#424 #423 Admin Navigation enhancement and better mobile view
  client/src/App.js
  client/src/components/Form.js
  client/src/components/Grid.js
  client/src/modules/admin/Container.js
  client/src/modules/admin/UnderConstruction.js
  client/src/modules/admin/index.js
  client/src/modules/admin/services/Container.js
  client/src/modules/admin/services/Nav.js
Labels: Front End

#431 #429 Fix: Admin Service > Create - Error Handling & Validation
  client/src/apis/utils.js
  client/src/modules/admin/services/Container.js
  client/src/resource/actions.js
  client/src/resource/reducer.js
  client/src/resource/sagas.js
Labels: Bug, Front End

#426 #425 Fix: Admin > Services > Create - Modifying positions not working properly
  client/src/modules/admin/services/Popup.js
Labels: Bug, Front End
