Repository efcsydney/efcsydney-roster, pull requests merged in 2018-09, with the labels that each got.

#439 #438
  docker/Entrypoint.sh
Labels: DevOps

#446 #445 UI Component > FormGroup - Add the helpText prop
  client/src/components/Form.js
  client/src/components/index.js
  client/src/i18n.js
  client/src/modules/admin/services/Popup.js
  client/src/modules/index/components/EditDay.js
Labels: Front End

#443 move `yarn db:migrate` after getting all files from S3
  docker/Entrypoint.sh
Labels: DevOps

#444 #441 Ability to audit the change logs on Admin
  api/controllers/changelogs-controller.js
  api/controllers/events-controller.js
  api/controllers/service-info-controller.js
  api/controllers/services-controller.js
  api/controllers/user-controller.js
  api/data/changelog-repository.js
  api/models/changelog.js
  api/schema/index.js
  api/schema/resolvers.js
  api/schema/types.js
  api/service/changelogs-service.js
  app.js
  client/package.json
  client/src/components/Grid.js
  client/src/index.js
  client/src/modules/admin/Container.js
  client/src/modules/admin/changelogs/Container.js
  client/src/modules/admin/changelogs/index.js
  client/yarn.lock
  db/migrate/20180831100903-create-changelog-table.js
  package.json
  yarn.lock
Labels: Back End, Front End

#449 Use PM2
  docker/Entrypoint.sh
  package.json
  process.json
  yarn.lock
Labels: Back End, DevOps
