Repository efcsydney/efcsydney-roster, pull requests merged in 2018-03, with the labels that each got.

#129 Email - Exclude some positions from showing
  api/service/send-email-service.js
  config/default.yaml
  scripts/email/utils.js
  test/unit-test/send-email-service-test.js
Labels: Back End, Front End

#175 Admin listing
  api/controllers/services-controller.js
  api/controllers/services-mock.json
  app.js
  client/src/App.js
  client/src/apis/services.js
  client/src/components/Button.js
  client/src/components/Grid.js
  client/src/components/index.js
  client/src/index.css
  client/src/modules/admin/Edit.js
  client/src/modules/admin/index.js
  package.json
  yarn.lock
Labels: Front End

#176 171 3 api put service
  api/controllers/events-controller.js
  api/controllers/service-info-controller.js
  api/controllers/services-controller.js
  api/data/service-repository.js
  api/mapper/dto-mapper.js
  api/models/calendar-date-frequency.js
  api/models/service-calendar-date.js
  api/service/services-service.js
Labels: Back End

#195 ELB cloudformation
  aws/ec2.json
  aws/elb.json
  aws/userdata
Labels: DevOps

#192 Admin > Edit - Integration with Save API
  client/src/apis/services.js
  client/src/modules/admin/index.js
Labels: Front End
