Repository efcsydney/efcsydney-roster, pull requests merged in 2018-05, with the labels that each got.

#239 #231
  client/src/modules/index/components/QuarterView/index.js
Labels: Bug, Front End

#253 Dockerize
  .dockerignore
  .gitignore
  .travis.yml
  Dockerfile-amazonlinux
  Dockerfile-dev
  Dockerfile-prod
  Entrypoint.sh
  config/database.json
  docker-compose.yml
  docker-manage.sh
  release.sh
Labels: DevOps

#269 #236: Ensure that the Service Title, Note Label are mandatory.
  client/src/modules/admin/services/Popup.js
Labels: Front End

#288 add database setting for 'docker' environment to database.json
  Entrypoint.sh
  config/database.json
  docker-compose.yml
Labels: Bug

#265 Ensure that you can change the order of the roles
  client/package.json
  client/src/components/DragDropZone.js
  client/src/components/DraggableItem.js
  client/src/components/index.js
  client/src/modules/admin/services/Popup.js
  client/yarn.lock
  package.json
  yarn.lock
Labels: Front End
